controller_list:
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_servo_1_joint
      - gripper_finger_1_joint
      - gripper_servo_2_joint
      - gripper_finger_2_joint
      - gripper_servo_3_joint
      - gripper_finger_3_joint
      - gripper_servo_4_joint
      - gripper_finger_4_joint
initial:  # Define initial robot poses per group
  - group: manipulator
    pose: AllZeroes